# Generated by Django 5.0.6 on 2024-06-22 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image_base64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
